language: python
python:
  - "2.7"
services: mongodb
# Apply only on main branches
branches:
  except:
    - /^feature.*$/
    - master
# command to install dependencies
before_install:
  - "sudo apt-get update -qq"
  - "sudo apt-get install -qq libldap2-dev libsasl2-dev"

install:
  - "pip install coverage"
  - "pip install python-coveralls"
  - "pip install -r requirements.txt --use-mirrors"
# command to run tests
script: nosetests --with-coverage --cover-package=mf
after_success:
  - coveralls
